### ISSUE TITLE
Ability to register modifiers

### ISSUE THREAD

**Issue by untitaker** [untitaker/iron-error-router#2]
Apparently modifiers don't have `Send` or `Sync`, so I don't know how this will work.

**Comment by reem** [comment]
@untitaker you should be able to require `M: Modifier + Send + Sync`? Modifiers consume themselves by-value though, so you may need `M: Modifier + Sync + Send + Clone`.

**Comment by untitaker** [comment]
IIRC most useful modifiers from Iron don't satisfy those requirements.

**Comment by reem** [comment]
It looks like the only modifiers which do not satisfy those requirements are `Box<WriteBody>` and `File`. `Path`, `PathBuf`, `String`, etc. all fulfill these bounds.

**Comment by untitaker** [comment]
AFAICT the `Header` and `Redirect` are missing it as well.

Creating a `Box<Modifier<Response> + Clone>` (plus the other traits) is impossible due to https://doc.rust-lang.org/error-index.html#E0225, so this is moot anyway: It's probably not possible to store modifiers in the mapping. However, we still might be able to store factory functions...?

**Comment by reem** [comment]
One possible scheme would look like:

``` rust
trait ModifierInner: Modifier<Response> + Send + Sync + Clone {
    fn clone_box(self: Box<Self>) -> Box<ModifierInner> {
        Box::new(self.clone())
    }

    fn apply_modify(self: Box<Self>, res: &mut Response) { self.modify(res) }
}

impl Modifier<Response> for Box<ModifierInner> {
    fn modify(self, res: &mut Response) { self.apply_modify(res) }
}
```

then you would take generic `M: Modifier<Response> + Send + Sync + Clone` and just store `Box<ModifierInner>` internally.

**Comment by reem** [comment]
Oh, actually replace those supertrait bounds on `ModifierInner` with a blanket impl for the same to maintain object safety.

**Comment by untitaker** [comment]
I couldn't find a way to have a "blanket impl" for Clone.

**Comment by reem** [comment]
Something like:

```
trait ModifierInner {
    fn clone_box(self: Box<Self>) -> Box<ModifierInner>;
    fn apply_modify(self: Box<Self>, res: &mut Response);
}

impl<M: Modifier<Response> + Send + Sync + Clone> ModifierInner for M {
    fn clone_box(self: Box<Self>) -> Box<ModifierInner> {
        Box::new(self.clone())
    }

    fn apply_modify(self: Box<Self>, res: &mut Response) { self.modify(res) }
}

impl Modifier<Response> for Box<ModifierInner> {
    fn modify(self, res: &mut Response) { self.apply_modify(res) }
}
```

**Comment by reem** [comment]
Now you can just store `Box<ModifierInner>` and clone it with `clone_box`.

**Comment by untitaker** [comment]
Ahh... this does get me a lot closer to a solution, but now I need ModifierInner to be Send + Sync because the whole struct that contains the Box is an AfterMiddleware!

**Comment by reem** [comment]
```
trait ModifierInner: Send + Sync {
    fn clone_box(self: Box<Self>) -> Box<ModifierInner>;
    fn apply_modify(self: Box<Self>, res: &mut Response);
}

impl<M: Modifier<Response> + Send + Sync + Clone> ModifierInner for M {
    fn clone_box(self: Box<Self>) -> Box<ModifierInner> {
        Box::new(self.clone())
    }

    fn apply_modify(self: Box<Self>, res: &mut Response) { self.modify(res) }
}

impl Modifier<Response> for Box<ModifierInner> {
    fn modify(self, res: &mut Response) { self.apply_modify(res) }
}
```

should do it.

**Comment by untitaker** [comment]
Now I get:

```
 the trait `modifier::Modifier<iron::response::Response>` is not implemented for the type `Box<M>`
```

For this line:

```
Box::new(self.clone())
```

**Comment by reem** [comment]
@untitaker are you sure you have the bound on M right? It should include `M: Modifier<Response>` which would eliminate that issue.

**Comment by untitaker** [comment]
Pull request in a minute. I'm sure.

**Comment by untitaker** [comment]
https://github.com/untitaker/iron-error-router/pull/4

**Comment by reem** [comment]
Try `Box::new(*self.clone())`, I think it's try to do `Box<Box<M>>` -> `Box<ModifierInner>`.

**Comment by untitaker** [comment]
Now I get lifetime issues, M may not live long enough.

**Comment by reem** [comment]
Add `M: 'static` to the impl.

**Comment by untitaker** [comment]
I managed to get it to compile! There was an additional lifetime issue which I mitigated by changing the signature of clone_box. Thanks!
